name: 'cerberus-secrets'
description: 'GitHub Actions to read secrets from Cerberus'
author: 'James Michael'
inputs:
  cerberusUrl:
    required: true
    description: 'Cerberus SDB path from where a secret to be read'
  cerberusRegion:
    required: false
    description: 'Cerberus Region to authenticate with'
  sdbPath:
    required: true
    description: 'Cerberus SDB path from where a secret to be read'
  sdbEnvVariableMapping:
    required: true
    description: 'Cerberus SDB keys and target environment variable names eg: [{"id": "ID", "name": "NAME", "url": "URL"}]'
runs:
  using: 'node12'
  main: 'dist/index.js'
