# Example workflow to demonstrate the action usage
name: 'example-with-iam-role'
on: [workflow_dispatch]

jobs:
  example:
    runs-on: self-hosted # A self hosted runner which already assumes the required IAM role
    name: Using Cerberus
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cerberus Action
        uses: ./
        id: run-cerberus
        with:
          cerberusUrl: ${{ secrets.CERBERUS_URL }}
          cerberusRegion: ${{ secrets.CERBERUS_REGION }}
          sdbPath: 'app/cdservice/cicduser'
          sdbEnvVariableMapping: '{"username": "MY_USERNAME", "password": "MY_PASSWORD"}'
      - name: Verify Variables in ENV
        env:
          TEST_STEP_VAR: 'ThisIsATestString'
        run: 'echo $MY_USERNAME && echo $MY_PASSWORD && echo $TEST_STEP_VAR'
