# Example workflow to demonstrate the action usage
name: 'example-with-cerberus-token'
on: [workflow_dispatch]

jobs:
  example:
    runs-on: self-hosted
    name: Using Cerberus
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cerberus Action
        uses: ./
        id: run-cerberus
        env:
          CERBERUS_TOKEN: ${{ secrets.CERBERUS_TOKEN }}
        with:
          cerberusUrl: ${{ secrets.CERBERUS_URL }}
          cerberusRegion: ${{ secrets.CERBERUS_REGION }}
          sdbPath: 'shared/github-actions-example/exampleapp'
          sdbEnvVariableMapping: '{"username": "MY_USERNAME", "password": "MY_PASSWORD"}'
      - name: Verify Variables in ENV
        env:
          TEST_STEP_VAR: 'ThisIsATestString'
        run: 'echo $MY_USERNAME && echo $MY_PASSWORD && echo $TEST_STEP_VAR'
